version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ordersapi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1iwgq40w67rtr"
s3_prefix = "ordersapi"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
