AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  orderapitest

  Sample SAM Template for orderapitest

Globals:
   Function:
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 30
      Environment: 
       Variables:
        ORDERS_TABLE: !Ref OrdersTable

Resources:
  OrdersTable:
   Type: AWS::Serverless::SimpleTable
   Properties:
    PrimaryKey:
      Name: id
      Type: Number

  CreateOrderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ordersapi
      Handler: com.co.aws.lambda.apis.CreateOrderLambda::createOrder
      Policies:
        - DynamoDBCrudPolicy:
             TableName: !Ref OrdersTable
      Events: 
        OrderEvents:
         Type: Api
         Properties:
           Path: /orders
           Method: POST
  ReadOrderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ordersapi
      Handler: com.co.aws.lambda.apis.ReadOrdersLambda::getOrders
      Policies:
        - DynamoDBReadPolicy:
             TableName: !Ref OrdersTable
      Events: 
        OrderEvents:
         Type: Api
         Properties:
           Path: /orders
           Method: GET

Outputs:
 CreateOrdersAPI:
  Description: "API GATEWAY ENDPOINT URL FOR CREATE ORDERS FUNCTION"
  Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/orders"
CreateOrderFunction:
  Description: "Lambda para crear un servicio"
  Value: !GetAtt CreateOrderFunction.Arn
CreateOrderFunctionIamRole:
  Description: "Create Order Lambda function IAM role ARN"
  Value: !GetAtt CreateOrderFunctionRole.Arn